#!/bin/bash
# OpenClaw Issue 处理脚本
# 用法：./scripts/process-issue.sh <issue_number>

set -e

ISSUE_NUMBER=$1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_FILE="$PROJECT_ROOT/logs/issue-${ISSUE_NUMBER}.log"

# 日志函数
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

if [ -z "$ISSUE_NUMBER" ]; then
    echo "❌ 用法：$0 <issue_number>"
    exit 1
fi

log "🚀 开始处理 Issue #$ISSUE_NUMBER"

# 1. 更新 Issue 状态为 processing
log "📝 更新 Issue 状态为 openclaw-processing..."
gh issue edit "$ISSUE_NUMBER" --add-label "openclaw-processing"
gh issue edit "$ISSUE_NUMBER" --remove-label "openclaw-new"
gh issue comment "$ISSUE_NUMBER" --body "🤖 **OpenClaw 已开始处理此 Issue**

- **时间**: $(date '+%Y-%m-%d %H:%M:%S %Z')
- **状态**: openclaw-processing
- **预计完成时间**: 30 分钟内"

# 2. 获取 Issue 详情
log "📋 获取 Issue 详情..."
ISSUE_TITLE=$(gh issue view "$ISSUE_NUMBER" --json title --jq '.title')
ISSUE_BODY=$(gh issue view "$ISSUE_NUMBER" --json body --jq '.body')

log "Issue 标题：$ISSUE_TITLE"
log "Issue 描述：${ISSUE_BODY:0:200}..."

# 3. 创建功能分支
BRANCH_NAME="feature/issue-${ISSUE_NUMBER}"
log "🌿 创建分支：$BRANCH_NAME"

# 检查分支是否已存在
if git show-ref --verify --quiet refs/heads/"$BRANCH_NAME"; then
    log "⚠️ 分支已存在，删除旧分支"
    git branch -D "$BRANCH_NAME"
fi

git checkout -b "$BRANCH_NAME"

# 4. 使用 opencode 进行开发
log "💻 开始开发..."
if command -v opencode &> /dev/null; then
    cd "$PROJECT_ROOT"
    
    # 创建 opencode 会话
    opencode run "实现 GitHub Issue #$ISSUE_NUMBER: $ISSUE_TITLE

需求描述：
$ISSUE_BODY

要求：
1. 遵循项目现有代码风格
2. 添加必要的注释
3. 确保代码可编译/可运行
4. 如有必要，添加测试用例

请在当前分支中实现以上功能。" || {
        log "❌ opencode 开发失败"
        gh issue edit "$ISSUE_NUMBER" --add-label "openclaw-error"
        gh issue comment "$ISSUE_NUMBER" --body "❌ **处理失败**

opencode 代码生成失败。请人工介入。

🤖 _OpenClaw Auto Dev_"
        exit 1
    }
else
    log "⚠️ opencode 未安装，跳过自动开发"
fi

# 5. 提交代码
log "💾 提交代码..."
cd "$PROJECT_ROOT"
git add -A

if git diff --staged --quiet; then
    log "⚠️ 没有更改需要提交"
else
    git commit -m "feat: 实现 Issue #$ISSUE_NUMBER - $ISSUE_TITLE

- 自动生成的实现
- OpenClaw Auto Dev"
    log "✅ 代码提交成功"
fi

# 6. 推送到远程
log "📤 推送到远程..."
git push -u origin "$BRANCH_NAME" || {
    log "❌ 推送失败"
    gh issue edit "$ISSUE_NUMBER" --add-label "openclaw-error"
    exit 1
}

# 7. 创建 PR
log "🔀 创建 Pull Request..."
PR_URL=$(gh pr create \
    --title "解决 Issue #$ISSUE_NUMBER: $ISSUE_TITLE" \
    --body "此 PR 解决 Issue #$ISSUE_NUMBER

## 变更内容
- 自动生成的实现
- OpenClaw Auto Dev

## 测试
- [ ] 已测试相关功能

## 检查清单
- [ ] 代码符合规范
- [ ] 添加了必要的注释
- [ ] 无编译错误

---
🤖 _Generated by OpenClaw Auto Dev_" \
    --head "$BRANCH_NAME" \
    --base "main")

log "✅ PR 创建成功：$PR_URL"

# 8. 更新 Issue 状态
log "🏷️ 更新 Issue 标签..."
gh issue edit "$ISSUE_NUMBER" --add-label "openclaw-pr-created"
gh issue comment "$ISSUE_NUMBER" --body "✅ **PR 已创建！**

PR: $PR_URL

请审核代码并决定是否合并。

🤖 _OpenClaw Auto Dev_"

log "🎉 Issue #$ISSUE_NUMBER 处理完成！"
echo "$PR_URL"
