#!/bin/bash
# OpenClaw Auto Dev - Issue 处理脚本
# 自动处理 openclaw-new Issue 的完整流程

set -euo pipefail

# 启用调试模式（可选）
# set -x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_DIR="$PROJECT_ROOT/logs"
LOG_FILE="$LOG_DIR/process-$(date '+%Y-%m-%d').log"

# 确保日志目录存在
mkdir -p "$LOG_DIR"

# 日志函数
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# 错误处理函数
error_exit() {
    log "❌ 错误：$1"
    # 更新 Issue 状态为 error
    if [ -n "$ISSUE_NUMBER" ]; then
        gh issue edit "$ISSUE_NUMBER" \
            --remove-label "openclaw-processing" \
            --add-label "openclaw-error" \
            --repo "$REPO" || true
    fi
    exit 1
}

# 配置
REPO="neiliuxy/openclaw-auto-dev"
ISSUE_NUMBER="${1:-}"

if [ -z "$ISSUE_NUMBER" ]; then
    # 从 scan-result.json 读取
    if [ -f "$PROJECT_ROOT/scan-result.json" ]; then
        ISSUE_NUMBER=$(jq -r '.issue_number // empty' "$PROJECT_ROOT/scan-result.json")
    fi
fi

if [ -z "$ISSUE_NUMBER" ]; then
    log "ℹ️ 没有需要处理的 Issue"
    exit 0
fi

log "=========================================="
log "🚀 开始处理 Issue #$ISSUE_NUMBER"
log "=========================================="

# 步骤 1: 获取 Issue 信息
log "📋 获取 Issue 信息..."
ISSUE_TITLE=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json title --jq '.title')
ISSUE_BODY=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json body --jq '.body')

log "📝 Issue 标题：$ISSUE_TITLE"
log "📄 Issue 描述：${ISSUE_BODY:-空}"

# 步骤 2: 创建分支
BRANCH_NAME="openclaw/issue-$ISSUE_NUMBER"
log "🌿 创建分支：$BRANCH_NAME"

# 确保在 master 分支
git checkout master
git pull origin master

# 创建并切换到新分支
if git show-ref --verify --quiet refs/heads/"$BRANCH_NAME"; then
    log "⚠️ 分支已存在，删除并重新创建"
    git branch -D "$BRANCH_NAME" || true
fi

git checkout -b "$BRANCH_NAME"

# 步骤 3: 更新 Issue 标签为 processing
log "🏷️ 更新 Issue 标签为 openclaw-processing..."
gh issue edit "$ISSUE_NUMBER" \
    --remove-label "openclaw-new" \
    --add-label "openclaw-processing" \
    --repo "$REPO"

# 步骤 4: 根据 Issue 内容开发/解决问题
log "💻 开始开发/解决问题..."

# 解析 Issue 标题，判断任务类型
case "$ISSUE_TITLE" in
    *"hello world"*|*"Hello World"*|*"C++"*)
        log "📝 任务类型：C++ Hello World 程序"
        
        # 创建 C++ Hello World 程序
        cat > hello.cpp <<'EOF'
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
EOF
        
        # 创建 Makefile
        cat > Makefile <<'EOF'
CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra

hello: hello.cpp
	$(CXX) $(CXXFLAGS) -o hello hello.cpp

clean:
	rm -f hello

.PHONY: clean
EOF
        
        # 创建 README
        cat > HELLO_README.md <<EOF
# Hello World in C++

这是一个简单的 C++ Hello World 程序。

## 编译

\`\`\`bash
make
\`\`\`

## 运行

\`\`\`bash
./hello
\`\`\`

## 输出

\`\`\`
Hello, World!
\`\`\`

---
Generated by OpenClaw Auto Dev 🦞
EOF
        
        git add hello.cpp Makefile HELLO_README.md
        COMMIT_MSG="feat: add C++ Hello World program (closes #$ISSUE_NUMBER)"
        ;;
    
    *"Python"*)
        log "🐍 任务类型：Python 相关"
        # TODO: 实现 Python 任务处理
        echo "# Python Task" > task.py
        git add task.py
        COMMIT_MSG="feat: add Python task template (closes #$ISSUE_NUMBER)"
        ;;
    
    *"JavaScript"*|*"JS"*)
        log "📜 任务类型：JavaScript 相关"
        # TODO: 实现 JS 任务处理
        echo "// JavaScript Task" > task.js
        git add task.js
        COMMIT_MSG="feat: add JavaScript task template (closes #$ISSUE_NUMBER)"
        ;;
    
    *)
        log "📋 任务类型：通用任务"
        # 创建通用的解决方案文件
        cat > "SOLUTION-$ISSUE_NUMBER.md" <<EOF
# Solution for Issue #$ISSUE_NUMBER

## Issue
$ISSUE_TITLE

## Description
${ISSUE_BODY:-No description provided}

## Solution
[Solution details here]

## Testing
[Test instructions here]

---
Generated by OpenClaw Auto Dev 🦞
EOF
        git add "SOLUTION-$ISSUE_NUMBER.md"
        COMMIT_MSG="feat: add solution for issue #$ISSUE_NUMBER"
        ;;
esac

# 步骤 5: 验证变更
log "🔍 验证变更..."
VALIDATION_SCRIPT="$SCRIPT_DIR/validate-changes.sh"
if [ -x "$VALIDATION_SCRIPT" ]; then
    # 传递 REPO 环境变量给验证脚本
    export REPO
    if ! "$VALIDATION_SCRIPT" "$ISSUE_NUMBER"; then
        log "❌ 验证失败，中止提交"
        # 恢复更改
        git reset --hard HEAD
        error_exit "变更验证失败"
    fi
    log "✅ 验证通过"
else
    log "⚠️ 验证脚本不存在或不可执行，跳过验证"
fi

# 步骤 6: 提交更改
log "📦 提交更改..."
git add -A
git commit -m "$COMMIT_MSG"

# 步骤 7: 推送到远程分支
log "📤 推送到远程分支..."
git push -u origin "$BRANCH_NAME"

# 步骤 8: 创建 PR
log "🔀 创建 Pull Request..."
PR_TITLE=$(gh pr create \
    --title "Fix: $ISSUE_TITLE" \
    --body "This PR addresses Issue #$ISSUE_NUMBER

## Changes
- Automated fix by OpenClaw Auto Dev 🦞

## Checklist
- [ ] Code reviewed
- [ ] Tests passed
- [ ] Documentation updated

Closes #$ISSUE_NUMBER" \
    --repo "$REPO" \
    --base master \
    --head "$BRANCH_NAME")

# 提取 PR 编号（gh pr create 返回 URL，需要从 URL 或列表中提取）
PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --repo "$REPO" --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
    log "✅ PR #$PR_NUMBER 已创建"
else
    log "⚠️ 无法提取 PR 编号"
    PR_NUMBER="unknown"
fi

# 步骤 9: 更新 Issue 标签为 pr-created
log "🏷️ 更新 Issue 标签为 openclaw-pr-created..."
gh issue edit "$ISSUE_NUMBER" \
    --remove-label "openclaw-processing" \
    --add-label "openclaw-pr-created" \
    --repo "$REPO"

# 步骤 10: 自动合并 PR
log "🔀 等待 CI 检查（3 秒）..."
sleep 3

log "✅ 合并 Pull Request..."
# 使用 --auto 让 GitHub 在 CI 通过后自动合并，或立即合并
MERGE_RESULT=$(gh pr merge "$PR_NUMBER" \
    --repo "$REPO" \
    --merge \
    --subject "Fix: $ISSUE_TITLE" \
    --body "Automatically merged by OpenClaw Auto Dev 🦞" 2>&1) || {
    log "⚠️ PR 合并命令执行失败：$MERGE_RESULT"
    log "⚠️ 尝试使用 API 直接合并..."
    gh api repos/"$REPO"/pulls/"$PR_NUMBER"/merge -X PUT \
        -f merge_method=merge \
        -f commit_title="Fix: $ISSUE_TITLE" \
        -f commit_message="Automatically merged by OpenClaw Auto Dev 🦞" || {
        log "❌ PR 合并失败，可能需要人工介入"
        error_exit "PR 合并失败"
    }
}

log "✅ 等待合并完成（2 秒）..."
sleep 2

# 验证合并状态
MERGE_STATUS=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json merged --jq '.merged')
if [ "$MERGE_STATUS" != "true" ]; then
    log "⚠️ PR 合并状态验证失败，当前状态：$MERGE_STATUS"
    log "⚠️ 继续执行后续步骤..."
fi

# 步骤 11: 更新 Issue 标签为 completed
log "🏷️ 更新 Issue 标签为 openclaw-completed..."
gh issue edit "$ISSUE_NUMBER" \
    --remove-label "openclaw-pr-created" 2>/dev/null || true \
    --add-label "openclaw-completed" \
    --repo "$REPO"

# 步骤 12: 关闭 Issue
log "✅ 关闭 Issue..."
gh issue close "$ISSUE_NUMBER" --repo "$REPO"

# 步骤 13: 删除远程分支
log "🧹 清理分支..."
git checkout master
git pull origin master

# 检查分支是否存在再删除
if git show-ref --verify --quiet refs/heads/"$BRANCH_NAME"; then
    git branch -D "$BRANCH_NAME"
    log "✅ 本地分支已删除"
else
    log "ℹ️ 本地分支不存在，跳过删除"
fi

if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
    git push origin --delete "$BRANCH_NAME" || true
    log "✅ 远程分支已删除"
else
    log "ℹ️ 远程分支不存在，跳过删除"
fi

# 生成完成报告
cat > "$PROJECT_ROOT/scan-result.json" <<EOF
{
    "timestamp": "$(date -Iseconds)",
    "status": "completed",
    "message": "Issue #$ISSUE_NUMBER 已处理完成",
    "issue_number": $ISSUE_NUMBER,
    "issue_title": "$(echo "$ISSUE_TITLE" | jq -Rs '.[:-1]')",
    "pr_number": $PR_NUMBER,
    "branch": "$BRANCH_NAME"
}
EOF

log "=========================================="
log "✅ Issue #$ISSUE_NUMBER 处理完成！"
log "   PR: #$PR_NUMBER"
log "   分支：$BRANCH_NAME (已删除)"
log "=========================================="

# 返回到 master 分支
git checkout master
